app:
  name: "starter"
  version: "1.0.0"
  mode: "debug" # debug, release, test
  port: 8080
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 120s
  max_header_bytes: 1048576 # 1MB

driver: "sqlite" # mysql, postgres, sqlite

database:
  enabled: true
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  db_name: "starter"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conn: 10
  max_open_conn: 100
  conn_max_life_time: 3600s
  table_prefix: ""
  show_log: true
  slow_threshold: 200ms

jwt_auth:
  secret: "your-secret-key"
  issuer: "starter"
  expire: 86400 # 24小时
  refresh_expire: 604800 # 7天
  blacklist_grace_period: 30 # 30秒

mongo:
  enabled: false
  uri: "mongodb://localhost:27017"
  user: ""
  password: ""
  db: "starter"

redis:
  instances:
    default:
      enabled: true
      addr: "localhost:6379"
      password: ""
      db: 0
      min_idle_conn: 10
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
      pool_size: 100
      pool_timeout: 4s
      enable_trace: false
    session:
      enabled: false
      addr: "localhost:6379"
      password: ""
      db: 1
      min_idle_conn: 5
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
      pool_size: 50
      pool_timeout: 4s
      enable_trace: false
  cache:
    default_ttl: 30m
    key_prefix: "cache:"
    enable_prewarm: true
    enable_protection: true
    protection_timeout: 5s
    nil_value_ttl: 1m
    local_cache: false
    local_cache_ttl: 5m
    local_cache_size: 10000

log:
  level: "debug" # debug, info, warn, error, fatal
  format: "console" # console, json
  output: "stdout" # stdout, stderr, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_age: 7 # days
  max_backups: 10
  compress: false
  caller: true
  stack_trace: true

casbin:
  model_path: "configs/casbin_model.conf"
  policy_adapter: "file" # file, mysql, postgres, sqlite
  policy_path: "configs/casbin_policy.csv"
  log_enabled: true
  auto_load: true
  auto_load_interval: 60 # seconds

storage:
  enabled: true
  type: "local" # local, s3, oss
  local:
    path: "storage"
    url: "/static"
  s3:
    access_key: ""
    secret_key: ""
    region: ""
    bucket: ""
    endpoint: ""
  path_config:
    avatar: "avatars"
    upload: "uploads"
    temp: "temp"

admin:
  username: "admin"
  password: "admin123"
  email: "admin@example.com"
  user_mode: "separate" # separate(分离模式), simple(简单模式)

grpc:
  enabled: false
  port: 9000
  reflection: true
  health_check: true
  read_timeout: 5s
  write_timeout: 5s

i18n:
  default_language: "zh-CN"
  languages: ["zh-CN", "en-US"]
  resources_path: "configs/i18n"
