APP:
  Port: 8058
Database:
  Username: root # 填写你的数据库账号
  Password: password # 填写你的数据库密码
  Host: 127.0.0.1 # 填写你的数据库地址
  Port: 3306
  DBName: starter
  TablePrefix:
  Charset: utf8mb4
  ParseTime: True
  Loc: "Local"
  LogMode: info
  MaxIdleConns: 10
  MaxOpenConns: 300
JwtAuth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 2592000

Log:
  Level: info                 # 日志级别: debug, info, warn, error
  Output: [console, file]     # 输出方式: console, file
  FileConfig:
    Path: ./logs/app.log      # 日志文件路径
    MaxSize: 100              # 每个日志文件的最大大小（MB）
    MaxAge: 7                 # 日志文件保留天数
    MaxBackups: 10            # 保留的旧日志文件最大数量
    Compress: true            # 是否压缩旧日志文件
